export interface TaxonomyItem {
  id: string;
  label: string;
  keywords: string[];
  hours: number;       // estimated hours lost per case
  preventable: boolean;
  color: string;
}

export const ISSUE_TAXONOMY: TaxonomyItem[] = [
  {
    id: 'load_ref',
    label: 'Missing Load Reference',
    keywords: [
      'load ref','loadref','load reference','without reference','no reference',
      'ref missing','booking ref','booking number','without booking','reference number',
      'load number','without load','no load ref','missing reference',
      'no ref','ref not provided','ref number missing','ref number not','no booking number',
      'reference not found','reference not provided','without load number','load ref not',
      'order reference','order number missing','po number missing','po number not',
      'purchase order missing','without po','shipment reference','shipment ref',
      'consignment number missing','no consignment ref','job reference','job number missing',
    ],
    hours: 0.5, preventable: true, color: '#dc6d7d',
  },
  {
    id: 'customs',
    label: 'Customs / Documentation',
    keywords: [
      'customs','douane','zoll','declaration','mrn','eur1','certificate of origin',
      'coo','phytosanitary','health cert','import license','export license',
      'commercial invoice','customs clearance','customs hold','customs inspection',
      'import declaration','export declaration','customs duty',
      'hs code','tariff code','commodity code','eori','eori number','vat number',
      'duty','import duty','export duty','customs broker','clearing agent',
      'customs agent','customs release','customs exam','customs delay','customs check',
      'ata carnet','carnet','bonded warehouse','bonded goods','customs entry',
      'customs value','customs documents','customs paperwork','missing documents',
      'documentation missing','documents not received','documents missing',
      'invoice missing','packing list','packing list missing','certificate missing',
      'compliance documents','regulatory documents','import compliance',
      'export compliance','sanctions','restricted goods','prohibited goods',
      'customs rejection','customs refusal','customs error','customs query',
    ],
    hours: 1.5, preventable: true, color: '#d8a34c',
  },
  {
    id: 'portbase',
    label: 'Portbase / Port Notification',
    keywords: [
      'portbase','port notification','port clearance','pre-notification',
      'port system','pcs message','ata notification','atd notification',
      'pre arrival','port entry','terminal notification',
      'port authority','harbour authority','port entry rejected','port access',
      'terminal access','gate notification','port pre-arrival','vessel notification',
      'shipping notification','port message','port admin','port documentation',
      'pre-arrival notification','arrival notification','departure notification',
      'port registration','port permit','berth notification','pilot notification',
    ],
    hours: 0.75, preventable: true, color: '#7aa2ff',
  },
  {
    id: 'bl',
    label: 'Bill of Lading (B/L)',
    keywords: [
      'bill of lading','b/l','sea waybill','original bl','telex release',
      'surrender bl','express bl','lading','bl correction','bl amendment',
      'release of bl','bl not received','bl missing',
      'hbl','mbl','house bl','master bl','house bill','master bill',
      'bl release','bl not available','bl draft','bl copy','bl original',
      'waybill','air waybill','awb','consignment note','cmr','cmr note',
      'bl error','bl incorrect','bl discrepancy','bl dispute','bl query',
      'shipping document','shipping release','cargo release','cargo documents',
      'original documents','original required','original not received',
    ],
    hours: 1.0, preventable: false, color: '#52c7c7',
  },
  {
    id: 't1',
    label: 'T1 / Transit Document',
    keywords: [
      't1 document','transit document','community transit','transit declaration',
      'transit entry','t1 missing','t1 error','t1 correction','transit pass',
      't1','t2','transit procedure','transit customs','transit mrn',
      'common transit','ncts','new computerised transit system','transit guarantee',
      'transit bond','transit principal','transit office','transit closure',
      'transit rejection','procedure 7100','transit not closed','transit open',
      'customs transit','in transit','transit status','transit movement',
    ],
    hours: 1.25, preventable: true, color: '#8b7cff',
  },
  {
    id: 'delay',
    label: 'Delay / Not On Time',
    keywords: [
      'delay','delayed','not on time','late arrival','late delivery','missed eta',
      'overdue','behind schedule','no show','punctuality','not arrived',
      'late collection','not collected','not delivered','running late',
      'not on-time','arrival delay',
      'eta passed','eta missed','past eta','later than expected','expected today',
      'not yet arrived','still waiting','waiting for delivery','waiting for collection',
      'postponed','rescheduled','held up','stuck','stranded','on hold',
      'behind time','time overrun','later than planned','not picked up','not picked-up',
      'failed delivery','failed collection','missed appointment','missed time slot',
      'slot missed','time slot overrun','delivery window','collection window missed',
      'vehicle not arrived','driver not arrived','truck not arrived','no driver',
      'driver late','driver delayed','vehicle delayed','truck delayed',
    ],
    hours: 2.0, preventable: false, color: '#dc6d7d',
  },
  {
    id: 'closing_time',
    label: 'Closing Time / Cutoff',
    keywords: [
      'closing time','cutoff','cut-off','cut off','vgm deadline','vgm cutoff',
      'closing deadline','missed cutoff','closing hour','after cutoff',
      'terminal cutoff','missed closing','before closing',
      'gate closed','terminal closed','closed gate','gate cutoff','gate cut off',
      'last entry','last admission','final cutoff','submission deadline',
      'filing deadline','vgm','verifiable gross mass','weight declaration deadline',
      'booking deadline','booking cutoff','arrival deadline','departure cutoff',
      'vessel cutoff','sailed without','missed vessel','missed ship','missed sailing',
      'missed departure','missed loading','too late for vessel','vessel already departed',
    ],
    hours: 0.5, preventable: true, color: '#d8a34c',
  },
  {
    id: 'amendment',
    label: 'Amendment / Correction',
    keywords: [
      'amendment','correction','amend','change request','modification',
      'update booking','booking change','rate correction','address correction',
      'consignee change','shipper change','booking amendment',
      'wrong address','incorrect address','address wrong','address error',
      'wrong weight','incorrect weight','weight change','weight amendment',
      'wrong volume','incorrect volume','volume change','wrong dimensions',
      'wrong description','incorrect description','description change',
      'wrong consignee','wrong shipper','wrong receiver','wrong sender',
      'wrong port','incorrect port','port change','wrong destination',
      'wrong origin','destination change','origin change','routing change',
      're-book','rebook','re book','revised booking','revised order',
      'update required','needs updating','please update','please correct',
      'please amend','please change','correction needed','wrong details',
      'incorrect details','booking error','booking mistake','data error',
    ],
    hours: 0.75, preventable: true, color: '#7aa2ff',
  },
  {
    id: 'waiting_time',
    label: 'Waiting Time / Demurrage',
    keywords: [
      'waiting time','demurrage','detention','wait time','waiting costs',
      'standing time','excessive wait','free time exceeded','storage costs',
      'container detention','chassis detention',
      'waiting at terminal','waiting at port','waiting at warehouse','waiting at depot',
      'long wait','extended wait','idle time','idle costs','standby costs',
      'standby time','congestion','port congestion','terminal congestion',
      'queue','queuing','in queue','queued','waiting in queue','waiting to load',
      'waiting to unload','waiting to discharge','waiting to collect',
      'free time','free period exceeded','storage charge','port storage',
      'terminal storage','quay rent','demurrage charge','detention charge',
      'additional storage','extra storage days','storage days exceeded',
    ],
    hours: 1.5, preventable: false, color: '#52c7c7',
  },
  {
    id: 'rate',
    label: 'Rate / Pricing / Invoice',
    keywords: [
      'rate query','pricing','rate dispute','invoice query','overcharge',
      'surcharge','freight rate','rate increase','quotation','tariff',
      'billing query','charge dispute','incorrect invoice','rate discrepancy',
      'invoice incorrect','wrong invoice','invoice wrong','invoice dispute',
      'overcharged','undercharged','charge query','charge incorrect','wrong charge',
      'unexpected charge','additional charge','extra charge','hidden charge',
      'fuel surcharge','emergency surcharge','peak season surcharge',
      'freight charge','handling charge','administrative charge',
      'quote','requote','re-quote','price query','price dispute','price increase',
      'cost query','cost increase','cost dispute','rate agreed','rate not agreed',
      'rate confirmation','rate not confirmed','credit note','credit query',
      'payment query','payment dispute','refund','refund request',
    ],
    hours: 0.5, preventable: false, color: '#8b7cff',
  },
  {
    id: 'damage',
    label: 'Damage / Loss / Claim',
    keywords: [
      'damage','damaged','cargo loss','lost cargo','missing cargo','shortfall',
      'cargo claim','breakage','contamination','stolen cargo','theft',
      'missing goods','shortage','goods missing',
      'broken','crushed','dented','scratched','torn','wet damage','water damage',
      'soaked','mould','mold','spoiled','spoilage','rotten','temperature damage',
      'freeze damage','heat damage','impact damage','transit damage','loading damage',
      'pilferage','pilfered','theft reported','goods stolen','partial loss',
      'total loss','claim submitted','claim filed','claim opened','insurance claim',
      'goods not delivered','delivery shortage','wrong goods','wrong quantity',
      'quantity wrong','quantity missing','quantity short','pieces missing',
      'units missing','pallets missing','boxes missing','cartons missing',
    ],
    hours: 3.0, preventable: false, color: '#dc6d7d',
  },
  {
    id: 'equipment',
    label: 'Container / Equipment',
    keywords: [
      'equipment issue','seal broken','reefer','temperature deviation','swap body',
      'container damage','trailer damage','faulty unit','defective container',
      'container unavailable','equipment shortage',
      'broken seal','seal damaged','seal missing','seal number wrong','seal discrepancy',
      'reefer failure','reefer breakdown','temperature exceedance','temperature alarm',
      'temperature out of range','cold chain','cold chain failure','genset','genset failure',
      'container not available','no container','container shortage','container delayed',
      'trailer not available','no trailer','truck breakdown','vehicle breakdown',
      'mechanical failure','mechanical issue','breakdown en route','vehicle defect',
      'flat tyre','tyre issue','engine failure','vehicle fault','equipment fault',
      'container dirty','container contaminated','container not suitable','unsuitable container',
      'wrong container type','wrong equipment type','equipment mismatch',
    ],
    hours: 1.0, preventable: false, color: '#d8a34c',
  },
  {
    id: 'tracking',
    label: 'Tracking / Visibility',
    keywords: [
      'tracking','where is','status update','no update','visibility',
      'track and trace','no tracking','not visible','no information',
      'whereabouts','location query','shipment status',
      'where are','where is my','what is the status','what is status','current status',
      'no status','status not updated','tracking not updated','tracking unavailable',
      'position unknown','location unknown','last known position','last update',
      'proof of delivery','pod','pod not received','pod missing','pod not available',
      'delivery confirmation','delivery proof','signed delivery','signature',
      'eta update','current eta','revised eta','new eta','expected arrival',
      'no visibility','blind shipment','no information available','cannot track',
    ],
    hours: 0.25, preventable: true, color: '#7aa2ff',
  },
  {
    id: 'communication',
    label: 'Communication / Escalation',
    keywords: [
      'no response','no reply','escalation','complaint','dissatisfied',
      'follow-up','follow up','unanswered','not answered',
      'poor communication','urgent escalation','no feedback',
      'cannot reach','unreachable','not reachable','not contactable','no contact',
      'not responding','unresponsive','not picking up','no answer','voicemail',
      'ignored','being ignored','not helped','no help','lack of response',
      'complaint about','unhappy','unsatisfied','not satisfied','disappointed',
      'frustrated','urgent','very urgent','extremely urgent','asap','as soon as possible',
      'escalate','escalating to','referring to management','management escalation',
      'service complaint','service failure','poor service','bad service',
      'not informed','not notified','should have been informed','no communication',
      'no notification','no alert','not told','not advised',
    ],
    hours: 0.5, preventable: true, color: '#52c7c7',
  },
  {
    id: 'other',
    label: 'Other / Unclassified',
    keywords: [],
    hours: 0.5, preventable: false, color: '#a6aec4',
  },
];

export const TAXONOMY_MAP = Object.fromEntries(ISSUE_TAXONOMY.map(t => [t.id, t]));
